language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
- 3.9-dev
- nightly
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: cRs9h7PXLYJUCz31jNARPz2lhz6c6YlLKwZe24bhQDyIH+6UDUkZYoVIuLmCZhIhRtcLHuH08hG4OIFIzSu+hBRp98euELJ/7mMGxcBZtuCo3s4nqc+lT6hRFGkFo4IQCZkj6oItZvnz2M0t5zWS48tUDzPC7t0GKjXPkSfiOptjnv6asv3S9ON62Bdh341bXyZyHewFdjd8jdZHjKl4tEJRSHuWE86f2K1qXT5DmMYrjy2hQaaPVedTaEd4u7/mN6ayCxgm/BDY92h6WnG1ybqCv8oDbNyVjXDyAtvmHS72F+K+s4q9IZiDDRwK7jW+TlXYoOSTWx8oLHEUfWlXMe2FvOcaLajmMlzSS/5VAvWlWMe7w/NLKDeqLAltrJwisbjGVHaNGljjDs8viVhns11EFuNiT/Kkr+mHJOU43WJG6WOkQw/G/7C5DVzbnwijuTrkbqOfc+ifvGE5U+YWCOJJUkXDye0keCMHcXdbArca+UIIS2WzTPuLa03/rD7fRiEUPgLtG229mA2vXZiq+evTQZXigqWbvdj44W9G7q1MZsReeNhbgtzmWtYYWPocxWEVme+8B83zmv9P/HaSgRADJvc1WcD+ApZ2clPGIk8dgVRWp9BFNvGqXH6kkBHJUY1wI2us4P90zYBnKylyk4umps9nT2vFB8YYjOuSLBw=
